itms/account/urls.py
from django.urls import path
from .views import *

app_name = "account"

# Account List
urlpatterns = [
    path("account_assign", account_assign, name="account_assign"),
    path("assign_account_action", assign_account_action, name="assign_account_action"),
    path("delete_account_action", delete_account_action, name="delete_account_action"),
]

# Account Type
urlpatterns += [
    path("account_type", account_type, name="account_type"),
    path("add_account_type", add_account_type, name="add_account_type"),
    path("edit_account_type", edit_account_type, name="edit_account_type"),
    path("delete_account_type/<slug:account_type_id>", delete_account_type, name="delete_account_type"),
]

itms/admin_itms/urls.py
from django.urls import path
from .views import *

app_name = "admin_itms"

# Account List
urlpatterns = [
    path("", admin_home, name="admin_home"),
    path("admin_reset_user_password", admin_reset_user_password, name="admin_reset_user_password"),
    path("admin_reset_password", admin_reset_password, name="admin_reset_password"),
]

urlpatterns += [
    path("admin_auth", admin_auth, name="admin_auth"),
    path("admin_add_user_auth", admin_add_user_auth, name="admin_add_user_auth"),
    path("admin_remove_user_auth", admin_remove_user_auth, name="admin_remove_user_auth"),
]

urlpatterns += [
    path("admin_auth_group", admin_auth_group, name="admin_auth_group"),
    path("admin_create_group_auth", admin_create_group_auth, name="admin_create_group_auth"),
    path("admin_add_group_auth", admin_add_group_auth, name="admin_add_group_auth"),
    path("admin_remove_group_auth", admin_remove_group_auth, name="admin_remove_group_auth"),
]

itms/api/urls.py
from django.urls import path
from .views import *

app_name = "api"

urlpatterns = []

itms/asset/urls.py
from django.urls import path
from .views import *

app_name = "asset"

urlpatterns = [
    path("laptop", laptop, name="laptop"),
    path("add_laptop", add_laptop, name="add_laptop"),
    path("upload_laptop_file", upload_laptop_file, name="upload_laptop_file"),
    path("edit_laptop", edit_laptop, name="edit_laptop"),
    path("delete_laptop", delete_laptop, name="delete_laptop"),
]

urlpatterns += [
    path("monitor", monitor, name="monitor"),
    path("add_monitor", add_monitor, name="add_monitor"),
    path("upload_monitor_file", upload_monitor_file, name="upload_monitor_file"),
    path("edit_monitor", edit_monitor, name="edit_monitor"),
    path("delete_monitor", delete_monitor, name="delete_monitor"),
]

urlpatterns += [
    path("asset_assign", asset_assign, name="asset_assign"),
    path("assign_asset_action", assign_asset_action, name="assign_asset_action"),
    path("delete_asset_action", delete_asset_action, name="delete_asset_action"),
    path("replace_asset_action", replace_asset_action, name="replace_asset_action"),
]

urlpatterns += [
    path("employee_asset_overview/<slug:employee_id>", employee_asset_overview, name="employee_asset_overview"),
    path("print_asset_hand_receipt/<slug:employee_id>", print_asset_hand_receipt, name="print_asset_hand_receipt"),
]

itms/employee/urls.py
from django.urls import path
from .views import *

app_name = "employee"

urlpatterns = [
    path("employee_list", employee_list, name="employee_list"),
    path("add_employee_form", add_employee_form, name="add_employee_form"),
    path("add_employee", add_employee, name="add_employee"),
    path("edit_employee_form/<slug:employee_id>", edit_employee_form, name="edit_employee_form"),
    path("edit_employee", edit_employee, name="edit_employee"),
    path("delete_employee", delete_employee, name="delete_employee"),
    path("deactivate_employee", deactivate_employee, name="deactivate_employee"),
    path("activate_employee", activate_employee, name="activate_employee"),
    path("employee_overview/<slug:employee_id>", employee_overview, name="employee_overview"),
]

itms/home/urls.py
from django.urls import path
from home.views import *
import home.views_account as account

# home url
urlpatterns = [
    path("", home, name="home"),
    path("test", test, name="test"),
]

# account maangement
urlpatterns += [
    path("login", account.itms_login, name="login"),
    path("logout", account.itms_logout, name="logout"),
    path("signup", account.itms_signup, name="signup"),
    path("change_password", account.itms_change_password, name="change_password"),
    path("profile", account.profile, name="profile"),
    # test
]

itms/itms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("", include("home.urls")),
    path("department/", include("department.urls")),
    path("logs/", include("logs.urls")),
    path("asset/", include("asset.urls")),
    path("employee/", include("employee.urls")),
    path("account/", include("account.urls")),
    path("api/", include("api.urls")),
    path("admin_itms/", include("admin_itms.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itms/home/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile", to_field="username")
    department = models.CharField(max_length=50, null=True)

itms/home/views.py
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from django.contrib.auth.models import User


# Create your views here.
@login_required
def home(request):
    return render(request, "home/home.html")


def test(request):
    return render(request, "home/test.html")

itms/home/templates/home/home.html
{% extends "root/base.html" %}
{% load static %}
{% block title %}ITMS Home{% endblock %}

{% block body_content %}
<div class='row'>
    <div class='col-sm-3'>
        <a href="{% url 'home' %}">
            <dash class='panel-body' >
                <h3 class='dash-text'>User</h3>
            </dash>
        </a>
        <div class="sub-menu-ul">
            <a href="{% url 'profile'%}">My Profile</a>
            <a href="{% url 'change_password'%}">Change Password</a>
            <a href="{% url 'admin_itms:admin_home' %}">Admin</a>
        </div>
    </div>
    <div class='col-sm-3'>
        <a href="{% url 'home' %}">
            <dash class='panel-body' >
                <h3 class='dash-text'>Department</h3>
            </dash>
        </a>
        <div class="sub-menu-ul">
            <a href="{% url 'department:cost_center'%}">Cost Center</a>
            <a href="{% url 'department:business_unit' %}">Businuss Unit</a>
            <a href="{% url 'home' %}">Businuss Group</a>
            <a href="{% url 'home' %}">Legal Entity</a>
        </div>
    </div>
    <div class='col-sm-3'>
        <a href="{% url 'home'%}">
            <dash class='panel-body' >
                <h3 class='dash-text'>Employee</h3>
            </dash>
        </a>
        <div class="sub-menu-ul">
            <a href="{% url 'employee:employee_list'%}"><b>Employee List</b></a>
            <a href="{% url 'account:account_type'%}">Accout Type </a>
            <a href="{% url 'account:account_assign'%}"><b>Assign Account</b></a>
        </div>
    </div>
    <div class='col-sm-3'>
        <a href="{% url 'home'%}">
            <dash class='panel-body' >
                <h3 class='dash-text'>Asset</h3>
            </dash>
        </a>
        <div class="sub-menu-ul">
            <a href="{% url 'asset:laptop'%}">Laptop</a>
            <a href="{% url 'asset:monitor'%}">Monitor</a>
            <a href="{% url 'asset:asset_assign'%}"><b>Assign Asset</b></a>
            <a href="{% url 'asset:asset_assign'%}">Asset History</a>
        </div>
    </div>
</div>

<div class='row'>
    <div class='col-sm-3'>
        <a href="{% url 'home' %}">
            <dash class='panel-body' >
                <h3 class='dash-text'>Developing</h3>
            </dash>
        </a>
        <div class="sub-menu-ul">
            <a href="{% url 'home' %}">Coming Soon</a>
            
        </div>
    </div>
</div>
{% endblock %}

itms/home/templates/home/test.html
{% extends "root/base.html" %}
<!-- HTML Main Content -->
{% load static %}
{% block title %}ITMS Test Page{% endblock %}
{% block header_links %}
    <li><i class='fa fa-list'></i> <a href='#'>This App</a></li> <!-- connect to CIMS -->
    <li><i class='far fa-circle'></i> <a href='#'>Sub Menu</a></li> <!-- connect to CIMS -->
    <li><i class='fa fa-circle'></i> <a href='#'>Active Sub Menu</a></li> <!-- connect to CIMS -->
{% endblock %}
{% block body_content%}
<div class='col-md-12 mt-4 row'>
    <div class='col-md-6'>
        <button type='button' class='btn btn-primary mt-2' id='search_btn'  onclick="show_json_message('success', 'success msg')" >Search</button>
    </div>
    <div class='col-md-6'>
        <button type='button' class='btn btn-danger mt-2 float-end' id='cancel_btn' onclick="show_json_message('error', 'error msg')">Cancel</button>
    </div>
</div>
<div class='col-md-12 mt-4 row'>
    <div class='col-md-2'>
        <input class='form-control' placeholder='input box'>
    </div>
    <div class='col-md-2'>
        <input readonly class='form-control' placeholder='input box'>
    </div>
    <div class='col-md-2'>
        <select class='form-control' id='active_select'>
            <option value='1'>One</option>
            <option value='2'>Two</option>
            <option value='3'>Three</option>
        </select>
    </div>
    <div class='col-md-2'>
        <select class='form-control' disabled id='disabled_select'>
            <option value='1'>One</option>
            <option value='2' selected>Two</option>
            <option value='3'>Three</option>
        </select>
    </div>
</div>
<div class='col-md-12 mt-4 row'>
    <h3>This is a table style example:</h3>
    <table class='table table-hover' >
        <thead>
            <tr class='table-header'>
                <th width='10%'>Work Order</th>
                <th width='10%'>Model (Sku)</th>
                <!-- <th width='10%'>Status</th> -->
                <th width='10%'>Target Qty</th>
                <th width='10%'>Scheduled Date</th>
                <th width='20%'>Tech Flow</th>
                <th width='25%'>Actions</th>
            </tr>
        </thead>
        <tbody class='bg-table'>
            <tr>
                <td>
                    <a href='#' class='ps-2'>123456789</a>
                </td>
                <td><a href='#'>3001</a></td>
                <!-- <td>{{ workorder.status}}</td> -->
                <td>5</td>
                <td>22-05-09</td>
                <td><a>This is a list of example of svg icons</a></td>
                <td>
                    <a  class='icon-text' href='#'>
                        <img class='image-size' src='/static/svg/accepted.svg' alt='accept wo'>
                        <span>Accept</span>
                    </a>
                    <a  class='icon-text'  href='#'>
                        <img class='image-size' src='/static/svg/release.svg' alt='generate pick list'>
                        <span>Gen Pick List</span>
                    </a>
                    <a  class='icon-text' href='#'>
                        <img class='image-size' src='/static/svg/generated.svg' alt='generate serial number'>
                        <span>Generate SN</span>
                    </a>
                    <a  class='icon-text' href='#'>
                        <img class='image-size' src='/static/svg/freezed.svg' alt='bind'>
                        <span>Bind Tech Flow</span>
                    </a>
                    <a  class='icon-text' href='#'>
                        <img class='image-size' src='/static/svg/submit-id-disabled.svg' alt='release'>
                        <span>Release WO</span>
                    </a>
                    <a  class='icon-text'>
                        <img class='image-size' src='/static/svg/re-import.svg' alt='re-import'>
                        <span>Re-Import</span>
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <a href='#' class='ps-2'>7789746</a>
                </td>
                <td><a href='#'>3002</a></td>
                <!-- <td>{{ workorder.status}}</td> -->
                <td>5</td>
                <td>22-05-09</td>
                <td><a>This is a list of example of font-awesome icons</a></td>
                <td>
                    <a  class='icon-text' href='#'>
                        <i class='fa fa-xmark fa-lg text-danger ms-4' ></i>
                        <span>Delete</span>
                    </a>
                    <a  class='icon-text'  href='#'>
                        <i class='fa fa-pen-to-square fa-lg text-primary ms-4' ></i>
                        <span>Edit</span>
                    </a>
                    <a  class='icon-text' href='#'>
                        <i class='fa fa-floppy-disk fa-lg text-primary ms-4' ></i>
                        <span>Save</span>
                    </a>
                    <a  class='icon-text' href='#'>
                        <i class='fa fa-plus fa-lg text-success ms-4' ></i>
                        <span>Add</span>
                    </a>
                    <a  class='icon-text' href='#'>
                        <i class='fa fa-angle-up fa-lg text-info ms-4' ></i>
                        <span>Collapse</span>
                    </a>
                    <a  class='icon-text'>
                        <i class='fa fa-angle-down fa-lg text-warning ms-4' ></i>
                        <span>Expand</span>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}