itms/account/urls.py
from django.urls import path
from .views import *

app_name = "account"

# Account List
urlpatterns = [
    path("account_assign", account_assign, name="account_assign"),
    path("assign_account_action", assign_account_action, name="assign_account_action"),
    path("delete_account_action", delete_account_action, name="delete_account_action"),
]

# Account Type
urlpatterns += [
    path("account_type", account_type, name="account_type"),
    path("add_account_type", add_account_type, name="add_account_type"),
    path("edit_account_type", edit_account_type, name="edit_account_type"),
    path("delete_account_type/<slug:account_type_id>", delete_account_type, name="delete_account_type"),
]

itms/api/urls.py
from django.urls import path
from .views import *

app_name = "api"

urlpatterns = []

itms/asset/urls.py
from django.urls import path
from .views import *

app_name = "asset"

urlpatterns = [
    path("laptop", laptop, name="laptop"),
    path("add_laptop", add_laptop, name="add_laptop"),
    path("upload_laptop_file", upload_laptop_file, name="upload_laptop_file"),
    path("edit_laptop", edit_laptop, name="edit_laptop"),
    path("delete_laptop", delete_laptop, name="delete_laptop"),
]

urlpatterns += [
    path("monitor", monitor, name="monitor"),
    path("add_monitor", add_monitor, name="add_monitor"),
    path("upload_monitor_file", upload_monitor_file, name="upload_monitor_file"),
    path("edit_monitor", edit_monitor, name="edit_monitor"),
    path("delete_monitor", delete_monitor, name="delete_monitor"),
]

urlpatterns += [
    path("asset_assign", asset_assign, name="asset_assign"),
    path("assign_asset_action", assign_asset_action, name="assign_asset_action"),
    path("delete_asset_action", delete_asset_action, name="delete_asset_action"),
    path("replace_asset_action", replace_asset_action, name="replace_asset_action"),
]

urlpatterns += [
    path("employee_asset_overview/<slug:employee_id>", employee_asset_overview, name="employee_asset_overview"),
    path("print_asset_hand_receipt/<slug:employee_id>", print_asset_hand_receipt, name="print_asset_hand_receipt"),
]

itms/employee/urls.py
from django.urls import path
from .views import *

app_name = "employee"

urlpatterns = [
    path("employee_list", employee_list, name="employee_list"),
    path("add_employee_form", add_employee_form, name="add_employee_form"),
    path("add_employee", add_employee, name="add_employee"),
    path("edit_employee_form/<slug:employee_id>", edit_employee_form, name="edit_employee_form"),
    path("edit_employee", edit_employee, name="edit_employee"),
    path("delete_employee", delete_employee, name="delete_employee"),
    path("deactivate_employee", deactivate_employee, name="deactivate_employee"),
    path("activate_employee", activate_employee, name="activate_employee"),
    path("employee_overview/<slug:employee_id>", employee_overview, name="employee_overview"),
]

itms/itms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("", include("home.urls")),
    path("department/", include("department.urls")),
    path("logs/", include("logs.urls")),
    path("asset/", include("asset.urls")),
    path("employee/", include("employee.urls")),
    path("account/", include("account.urls")),
    path("api/", include("api.urls")),
    path("admin_itms/", include("admin_itms.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itms/asset/models.py
from django.db import models


# Create your models here.
class Asset(models.Model):
    asset_type = models.CharField(max_length=127)
    asset_label = models.CharField(max_length=127, unique=True)
    brand = models.CharField(max_length=127)
    model = models.CharField(max_length=127, null=True)
    serial_number = models.CharField(max_length=127)
    purchase_date = models.DateTimeField(null=True)
    purchase_cost = models.DecimalField(max_digits=9, decimal_places=3)
    status = models.CharField(max_length=15, null=True)  # IDLE, IN_USE, RETIRED
    purchase_order_number = models.CharField(max_length=31, null=True)

    class Meta:
        abstract = True


class Laptop(Asset):
    processor = models.CharField(max_length=127, null=True)
    ram = models.CharField(max_length=15, null=True)
    storage = models.CharField(max_length=15, null=True)


class Monitor(Asset):
    screen_size = models.IntegerField(null=True)
    resolution = models.CharField(max_length=63)

itms/asset/views.py
from datetime import datetime
from decimal import *
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from asset.app_function import (
    assign_asset_to_user,
    check_asset,
    remove_asset_from_user,
    laptop_file_handling,
    check_laptop_add,
    check_monitor_add,
    monitor_file_handling,
)

from home.app_function import check_permission, get_paginated_obj, json_error, json_success
from employee.models import Employee, EmployeeAsset
from asset.models import Laptop, Monitor
from logs.models import LaptopLog, MonitorLog, AssetAssignLog


# Create your views here.
@login_required
def laptop(request):
    # can_view = check_permission(request.user, "asset.view_laptop")
    # if not can_view:
    #     messages.error(request, f"You do no have permission to view Laptop. ")
    #     return redirect("home")
    context = {}
    laptop_set = Laptop.objects.all().order_by("status", "brand", "asset_label")

    curr_search = request.GET.get("search", "").strip()
    if curr_search:
        laptop_set = laptop_set.filter(
            Q(asset_type__icontains=curr_search)
            | Q(asset_label__icontains=curr_search)
            | Q(brand__icontains=curr_search)
            | Q(model__icontains=curr_search)
            | Q(serial_number__icontains=curr_search)
            | Q(purchase_date__icontains=curr_search)
            | Q(purchase_cost__icontains=curr_search)
            | Q(status__icontains=curr_search)
            | Q(processor__icontains=curr_search)
            | Q(ram__icontains=curr_search)
            | Q(storage__icontains=curr_search)
        )
        context["curr_search"] = curr_search

    updated_context = get_paginated_obj(
        laptop_set, request.GET.get("page_num", 1), request.GET.get("page_obj_count", 10)
    )
    context.update(updated_context)

    return render(request, "asset/laptop.html", context)


@login_required
@csrf_exempt
def add_laptop(request):
    can_act, msg = check_permission(request.user, "asset.change_asset")
    if not can_act:
        messages.error(request, f"You do no have permission to add Laptop. {msg}")
        return redirect("asset:laptop")

    user_name = request.user.username

    asset_type = request.POST.get("asset_type", "").strip()
    asset_label = request.POST.get("asset_label", "").strip()
    brand = request.POST.get("brand", "").strip()
    model = request.POST.get("model", "").strip()
    serial_number = request.POST.get("serial_number", "").strip()
    processor = request.POST.get("processor", "").strip()
    ram = request.POST.get("ram", "").strip()
    storage = request.POST.get("storage", "").strip()
    purchase_date = request.POST.get("purchase_date", "").strip()
    purchase_cost = request.POST.get("purchase_cost", "").strip()

    status, msg, purchase_date, purchase_cost = check_laptop_add(
        ram, storage, purchase_date, purchase_cost, asset_label, serial_number
    )
    if status == "error":
        messages.error(request, msg)
        return redirect("asset:laptop")

    laptop_ref = Laptop.objects.filter(asset_label=asset_label).first()
    if laptop_ref:
        messages.error(request, f"Laptop {asset_label} already exists, use edit button. ")
        return redirect("asset:laptop")

    Laptop.objects.create(
        asset_type=asset_type,
        asset_label=asset_label,
        brand=brand,
        model=model,
        serial_number=serial_number,
        processor=processor,
        ram=ram,
        storage=storage,
        purchase_date=purchase_date,
        purchase_cost=purchase_cost,
        status="IDLE",
    )

    # create_log
    LaptopLog.create_log(
        "Add",
        asset_label,
        serial_number,
        user_name,
        f"{brand}, {model}, {processor}, {ram}, {storage}, {purchase_date}, {purchase_cost}, IDLE",
    )

    messages.success(request, f"Laptop {asset_label} added successfully.")
    return redirect("asset:laptop")


@login_required
@csrf_exempt
def upload_laptop_file(request):
    laptop_file = request.FILES["laptop_file"] if "laptop_file" in request.FILES else None
    user_name = request.user.username
    status, msg = laptop_file_handling(laptop_file, user_name)
    if status == "error":
        messages.error(request, msg)

    return redirect("asset:laptop")


@login_required
@csrf_exempt
def edit_laptop(request):
    can_act, msg = check_permission(request.user, "asset.change_asset")
    if not can_act:
        messages.error(request, f"You do no have permission to edit Laptop. {msg}")
        return redirect("asset:laptop")

    user_name = request.user.username

    asset_label = request.POST.get("asset_label", "").strip()
    brand = request.POST.get("brand", "").strip()
    model = request.POST.get("model", "").strip()
    serial_number = request.POST.get("serial_number", "").strip()
    processor = request.POST.get("processor", "").strip()
    ram = request.POST.get("ram", "").strip()
    storage = request.POST.get("storage", "").strip()
    purchase_date = request.POST.get("purchase_date", "").strip()
    purchase_cost = request.POST.get("purchase_cost", "").strip()
    status = request.POST.get("status", "").strip()

    if len(ram) > 15 or len(storage) > 15:
        messages.error(request, "Ram and Storage should not exceeds the allowed range. ")
        return redirect("asset:laptop")

    if purchase_date:
        purchase_date = datetime.strptime(purchase_date, "%Y-%m-%d").astimezone()
    else:
        purchase_date = None

    if purchase_cost:
        purchase_cost = Decimal(purchase_cost)
        if abs(purchase_cost) >= 10**6:
            messages.error(request, "Purchase Cost should not exceeds the allowed range. ")
            return redirect("asset:laptop")
    else:
        purchase_cost = 0

    if not asset_label:
        messages.error(request, "Asset Label cannot be empty. ")
        return redirect("asset:laptop")

    if not serial_number:
        messages.error(request, "SN cannot be empty. ")
        return redirect("asset:laptop")

    laptop_ref = Laptop.objects.filter(asset_label=asset_label).first()
    if not laptop_ref:
        messages.error(request, f"Laptop {asset_label} does not exist. ")
        return redirect("asset:laptop")

    msg = ""
    # if laptop_ref.status == "IN_USE" and (status == "IDLE" or status == "RETIRED"):
    #     employee_ref = Employee.objects.filter(laptop__asset_label=asset_label).first()
    #     employee_ref.laptop = None
    #     employee_ref.save()
    #     msg = f"(Employee {employee_ref.employee_id} lose Laptop {asset_label})"

    laptop_ref.asset_label = asset_label
    laptop_ref.brand = brand
    laptop_ref.model = model
    laptop_ref.serial_number = serial_number
    laptop_ref.processor = processor
    laptop_ref.ram = ram
    laptop_ref.storage = storage
    laptop_ref.purchase_date = purchase_date
    laptop_ref.purchase_cost = purchase_cost
    if status:
        laptop_ref.status = status
    else:
        status = laptop_ref.status

    laptop_ref.save()
    laptop_ref.refresh_from_db()

    # create_log
    LaptopLog.create_log(
        "Edit",
        asset_label,
        serial_number,
        user_name,
        f"{brand}, {model}, {processor}, {ram}, {storage}, {purchase_date}, {purchase_cost}, {status + msg}",
    )

    messages.success(request, f"Laptop {asset_label} edited successfully. " + msg)
    return redirect("asset:laptop")


@login_required
@csrf_exempt
def delete_laptop(request):
    can_act, msg = check_permission(request.user, "asset.change_asset")
    if not can_act:
        return json_error(f"You do no have permission to delete Laptop. {msg}")

    user_name = request.user.username

    laptop_id = request.POST.get("laptop_id", "").strip()
    comment = request.POST.get("comment", "").strip()

    laptop_ref = Laptop.objects.filter(id=laptop_id).first()
    if not laptop_ref:
        return json_error(f"Laptop {laptop_id} does not exist. ")

    # create_log
    LaptopLog.create_log(
        "Delete",
        laptop_ref.asset_label,
        laptop_ref.serial_number,
        user_name,
        f"comment: ({comment}), {laptop_ref.brand}, {laptop_ref.model},\
        {laptop_ref.processor}, {laptop_ref.ram}, {laptop_ref.storage}, {laptop_ref.purchase_date}, {laptop_ref.purchase_cost}, {laptop_ref.status}",
    )

    laptop_ref.delete()
    return json_success(f"Laptop {laptop_ref.asset_label} deleted successfully.")


# Create your views here.
@login_required
def monitor(request):
    # can_view = check_permission(request.user, "asset.view_monitor")
    # if not can_view:
    #     messages.error(request, f"You do no have permission to view Monitor. ")
    #     return redirect("home")
    context = {}
    monitor_set = Monitor.objects.all().order_by("status", "brand", "asset_label")

    curr_search = request.GET.get("search", "").strip()
    if curr_search:
        monitor_set = monitor_set.filter(
            Q(asset_type__icontains=curr_search)
            | Q(asset_label__icontains=curr_search)
            | Q(brand__icontains=curr_search)
            | Q(model__icontains=curr_search)
            | Q(serial_number__icontains=curr_search)
            | Q(purchase_date__icontains=curr_search)
            | Q(purchase_cost__icontains=curr_search)
            | Q(status__icontains=curr_search)
            | Q(screen_size__icontains=curr_search)
            | Q(resolution__icontains=curr_search)
        )
        context["curr_search"] = curr_search

    updated_context = get_paginated_obj(
        monitor_set, request.GET.get("page_num", 1), request.GET.get("page_obj_count", 10)
    )
    context.update(updated_context)

    return render(request, "asset/monitor.html", context)


@login_required
@csrf_exempt
def add_monitor(request):

itms/asset/templates/asset/asset_assign.html
{% extends "root/base_table_list.html" %}
{% load static %}
{% block title %}ITMS Asset{% endblock %}


{% block header_links %}
<li><i class='fa fa-list'></i> <a href="{% url 'employee:employee_list' %}">Employee List</a></li>
<li><i class='fa fa-circle'></i> <a href="{% url 'asset:asset_assign' %}">Assign Asset</a></li>
<li><i class='far fa-circle'></i> <a href="{% url 'account:account_assign' %}">Assign Account</a></li>

{% endblock %}

{% block header_nav_bar %}
<form method='GET' class='row pe-0'>
    <div class='col-md-2'>
        <input class='form-control' name='search' id='search' placeholder='Search Any Field' value='{{curr_search}}' autofocus='true'>
    </div>
    <div class='col-md-1 btn-row'>
        <button class='btn btn-primary'>Search</button>
    </div>
</form>
{% endblock %}

{% block table_list %}
<table class='table table-hover' >
    <thead>
        <tr class='table-header'>
            <th width='15%'>Employee ID</th>
            <th width='15%'>Name</th>
            <th width='20%'>Department</th>
            <th width='15%'>Supervisor</th>
            <th width='10%'>Asset Action</th>
        </tr>
    </thead>
    <tbody class='bg-table'>
    {% for employee_ref in objs %}
        <tr {% if not employee_ref.active %} class='bg-warning' {% endif %}>
            <td><a href="{% url 'employee:employee_overview' employee_id=employee_ref.employee_id %}">{{employee_ref.employee_id}}</a></td>
            <td>{{employee_ref.name}}</td>
            <td>{{employee_ref.department.cc_code}} -- {{employee_ref.department.cc_name}}</td>
            <td>{{employee_ref.supervisor}}</td>
            <td>
                <button class='btn btn-lg btn-primary' 
                    onclick="assign_asset('{{employee_ref.employee_id}}', '{{employee_ref.name}}')"
                >Assign</button>
                <a href="{% url 'asset:employee_asset_overview' employee_id=employee_ref.employee_id %}" class='cursor-pointer ms-2' title='Edit'><i class='fa fa-lg fa-edit'></i></a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block script_block %}

<script src="{% static 'asset/asset_assign.js' %}"></script>

{% endblock %}

itms/asset/templates/asset/employee_asset_overview.html
{% extends "root/base_table_list.html" %}
{% load static %}
{% block title %}ITMS Employee Asset{% endblock %}


{% block header_links %}
<li><i class='fa fa-list'></i> <a href="{% url 'employee:employee_list' %}">Employee List</a></li>
<li><i class='far fa-circle'></i> <a href="{% url 'asset:asset_assign' %}">Assign Asset</a></li>
<li><i class='fa fa-circle'></i> <a href="{% url 'asset:employee_asset_overview' employee_id=employee_ref.employee_id %}">Employee Asset: {{employee_ref.name}}</a></li>
{% endblock %}


{% block body_content %}

<main>
    <section class='wrapper'>
        <div class='row'>
            <div class='col-md-1'></div>
            <div class='col-md-10'>
                <div class='mb-3'>
                <a class='btn btn-primary' href="{% url 'asset:print_asset_hand_receipt' employee_id=employee_ref.employee_id %}" target="_blank" rel="noopener noreferrer">Print Custody Property Record</a>
                </div>
                <section class='card'>
                    <div id='employee_header' data-bs-toggle="collapse" data-bs-target="#employee_body">
                        <header class="card-header bg-primary fw-bold text-white">
                            Basic Information
                        </header>
                    </div>
                    <div class="card-body">
                        <div id='employee_body' class='collapse show'>
                            <div class='row mt-2'>
                                <div class='col-md-3'>
                                    <label>Employee ID:</label>
                                    <input class='form-control mt-2' readonly value='{{employee_ref.employee_id}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Join Date:</label>
                                    <input type='date' class='form-control mt-2' readonly value='{{employee_ref.join_date | date:"Y-m-d"}}'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                            </div>

                            <div class='row mt-2'>
                                <div class='col-md-3'>
                                    <label>First Name:</label>
                                    <input class='form-control mt-2' readonly value='{{employee_ref.first_name}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Preferred Name:</label>
                                    <input class='form-control mt-2' readonly value='{{employee_ref.preferred_name}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Middle Name:</label>
                                    <input class='form-control mt-2' readonly value='{{employee_ref.middle_name}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Last Name:</label>
                                    <input class='form-control mt-2' readonly value='{{employee_ref.last_name}}'>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section class='card mt-3'>
                    <div id='department_header' data-bs-toggle="collapse" data-bs-target="#department_body">
                        <header class="card-header bg-primary fw-bold text-white">
                            Department
                        </header>
                    </div>
                    <div class="card-body">
                        <div id='department_body' class='collapse show'>
                            <div class='row mt-2'>
                                <div class='col-md-3'>
                                    <label>Cost Center:</label>
                                    <input class='form-control mt-2' readonly value='{{ employee_ref.department.cc_code }} -- {{ employee_ref.department.cc_name }}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Supervisor:</label>
                                    <input class='form-control mt-2' readonly value='{{employee_ref.supervisor}}'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section class='card mt-3'>
                    <div id='asset_header' data-bs-toggle="collapse" data-bs-target="#asset_body">
                        <header class="card-header bg-primary fw-bold text-white">
                            Assets
                        </header>
                    </div>
                    <div class="card-body">
                        <div id='asset_body' class='collapse show'>
                            {% if asset_set %}
                                <table class='table'>
                                    <thead>
                                        <tr>
                                            <th width='10%'>Category</th>
                                            <th width='15%'>Label</th>
                                            <th width='10%'>SN</th>
                                            <th width='10%'>Brand</th>
                                            <th width='15%'>Model</th>
                                            <th width='15%'>Assign Date</th>
                                            <th width='15%'>Assign Person</th>
                                            <th width='10%'>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>                                        
                                        {% for asset in asset_set %}
                                            <tr>
                                                <td>{{asset.asset_type}}</td>
                                                <td>{{asset.asset_label}}</td>
                                                <td>{{asset.asset_serial_number}}</td>
                                                <td>{{asset.asset_brand}}</td>
                                                <td>{{asset.asset_model}}</td>
                                                <td>{{asset.assign_date|date:'Y-m-d H:i'}}</td>
                                                <td>{{asset.assign_person}}</td>
                                                <td>                
                                                    <a class='cursor-pointer' title='Replace' 
                                                        onclick="replace_asset('{{employee_ref.employee_id}}', '{{employee_ref.name}}', '{{asset.asset_type}}','{{asset.asset_label}}')"
                                                    ><i class='fa fa-lg fa-edit'></i></a>
                                                    <a class='cursor-pointer text-danger ms-3' title='Delete'
                                                    onclick="delete_asset('{{employee_ref.employee_id}}', '{{employee_ref.name}}', '{{asset.asset_type}}','{{asset.asset_label}}')"
                                                    ><i class='fa fa-lg fa-xmark'></i></a>
                                                </td>
                                            </tr>
                                            
                                        {% endfor %}                                            
                                    </tbody>
                                </table>
                            {% else %}
                                No asset is assigned to {{employee_ref.name}}
                            {% endif %}
                        </div>
                    </div>
                </section>
            </div>
            <div class='col-md-1'></div>
        </div>
    </section>
</main>

{% endblock %}

{% block script_block %}
    <script src="{% static 'asset/employee_asset_overview.js' %}"></script>
{% endblock %}

itms/asset/templates/asset/laptop.html
{% extends "root/base_table_list.html" %}
{% load static %}
{% block title %}ITMS Laptop{% endblock %}


{% block header_links %}
<li><i class='fa fa-list'></i> <a href="{% url 'employee:employee_list' %}">Employee List</a></li>
<li><i class='far fa-circle'></i> <a href="{% url 'asset:asset_assign' %}">Assign Asset</a></li>
<li><i class='fa fa-circle'></i> <a href="{% url 'asset:laptop' %}">Laptop</a></li>
<li><i class='far fa-circle'></i> <a href="{% url 'asset:monitor' %}">Monitor</a></li>
<li><a href='/media/SOP/Laptop_Excel_Template.xlsx' download='Laptop File Setup.xlsx' >&lt;Download Laptop File Template&gt;</a></li>
{% endblock %}

{% block header_nav_bar %}
<div class='row pe-0'>
    <form method='GET' id='test_record_form' class='col-md-6'>
        <div class='row'>
            <div class='col-md-4'>
                <input class='form-control' name='search' id='search' placeholder='Search Any Field' value='{{curr_search}}' autofocus='true'>
            </div>
            <div class='col-md-1 btn-row'>
                <button class='btn btn-primary'>Search</button>
            </div>
        </div>
    </form>
    <form method="POST" class='col-md-6' enctype="multipart/form-data" id='upload_laptop_file' action="{% url 'asset:upload_laptop_file' %}">
        <div class='row'>
            <div class='col-md-6'></div>
            <div class='col-md-4'>
                <label for='laptop_file' class='btn btn-outline-primary full-width' style='text-align:left'>
                    <span class='text-danger'>*</span> Upload Laptop File
                </label>
                <input hidden id='laptop_file' name='laptop_file' type='file' style='opacity: 0;' onchange="$('#upload_laptop_file').submit()">
            </div>
            <div class='col-md-2'>
                <button type='button' class='btn btn-primary' onclick="add_laptop()">
                    Add Laptop
                </button> 
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block table_list %}
<table class='table table-hover' >
    <thead>
        <tr class='table-header'>
            <th width='10%'>Asset Type</th>
            <th width='10%'>Asset Label</th>
            <th width='8%'>Brand</th>
            <th width='8%'>Model</th>
            <th width='8%'>SN</th>
            <th width='8%'>Processor</th>
            <th width='8%'>Ram(GB)</th>
            <th width='8%'>Storage(GB)</th>
            <th width='15%'>Purchase Date</th>
            <th width='10%'>Purchase Cost</th>
            <th width='10%'>Status</th>
            <th width='10%'>Action</th>
        </tr>
    </thead>
    <tbody class='bg-table'>
    {% for laptop_ref in objs %}
        <tr>
            <td>{{laptop_ref.asset_type}}</td>
            <td>{{laptop_ref.asset_label}}</td>
            <td>{{laptop_ref.brand}}</td>
            <td>{{laptop_ref.model}}</td>
            <td>{{laptop_ref.serial_number}}</td>
            <td>{{laptop_ref.processor}}</td>
            <td>{{laptop_ref.ram}}</td>
            <td>{{laptop_ref.storage}}</td>
            <td>{{laptop_ref.purchase_date | date:'Y-m-d'}}</td>
            <td>${{laptop_ref.purchase_cost}}</td>
            <td>{{laptop_ref.status}}</td>
            <td>
                <a class='cursor-pointer' title='Edit' 
                    onclick="edit_laptop('{{laptop_ref.asset_label}}', '{{laptop_ref.brand}}', '{{laptop_ref.model}}', 
                    '{{laptop_ref.serial_number}}', '{{laptop_ref.processor}}', '{{laptop_ref.ram}}', '{{laptop_ref.storage}}',
                    '{{laptop_ref.purchase_date | date:'Y-m-d'}}', '{{laptop_ref.purchase_cost}}', '{{laptop_ref.status}}')"
                ><i class='fa fa-lg fa-edit'></i></a>
                {% if laptop_ref.status == 'IDLE' %}
                <a class='cursor-pointer text-danger ms-3' title='Delete'
                onclick="delete_laptop('{{laptop_ref.id}}', '{{laptop_ref.asset_label}}','{{laptop_ref.serial_number}}')"
                ><i class='fa fa-lg fa-xmark'></i></a>
                {% else %}
                <a class='cursor-pointer text-dark ms-3' title='Delete' href='#'><i class='fa fa-lg fa-xmark'></i></a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}


{% block script_block %}

<script src="{% static 'asset/laptop.js' %}"></script>

{% endblock %}