itms/api/urls.py
from django.urls import path
from .views import *

app_name = "api"

urlpatterns = []

itms/department/urls.py
from django.urls import path
from .views import *

app_name = "department"

# Cost Center
urlpatterns = [
    path("cost_center", cost_center, name="cost_center"),
    path("add_cost_center", add_cost_center, name="add_cost_center"),
    path("edit_cost_center", edit_cost_center, name="edit_cost_center"),
    path("delete_cost_center/<slug:cc_id>", delete_cost_center, name="delete_cost_center"),
]

# Business Unit
urlpatterns += [
    path("business_unit", business_unit, name="business_unit"),
    path("add_business_unit", add_business_unit, name="add_business_unit"),
    path("edit_business_unit", edit_business_unit, name="edit_business_unit"),
    path("delete_business_unit/<slug:bu_id>", delete_business_unit, name="delete_business_unit"),
]

itms/itms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("", include("home.urls")),
    path("department/", include("department.urls")),
    path("logs/", include("logs.urls")),
    path("asset/", include("asset.urls")),
    path("employee/", include("employee.urls")),
    path("account/", include("account.urls")),
    path("api/", include("api.urls")),
    path("admin_itms/", include("admin_itms.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itms/logs/urls.py
from django.urls import path
from .views import *

app_name = "logs"
urlpatterns = [
    path("cost_center_log", cost_center_log, name="cost_center_log"),
    path("business_unit_log", business_unit_log, name="business_unit_log"),
]

itms/department/models.py
from django.db import models


# Create your models here.
class LegalEntity(models.Model):
    le_name = models.CharField(max_length=63, null=True, unique=True)


class BusinessGroup(models.Model):
    bg_name = models.CharField(max_length=63, null=True)
    bg_manager = models.CharField(max_length=127, null=True)
    le = models.ForeignKey(
        LegalEntity, on_delete=models.SET_NULL, null=True, to_field="le_name", related_name="bg_set"
    )


class BusinessUnit(models.Model):
    bu_name = models.CharField(max_length=63, null=True)
    bg_name = models.CharField(max_length=63, null=True)
    bg = models.ForeignKey(BusinessGroup, on_delete=models.SET_NULL, null=True, related_name="bu_set")
    bu_manager = models.CharField(max_length=127, null=True)
    le_name = models.CharField(max_length=63, null=True)


class CostCenter(models.Model):
    cc_code = models.CharField(max_length=31)
    cc_name = models.CharField(max_length=63)
    cc_manager = models.CharField(max_length=127, null=True)
    bu = models.ForeignKey(BusinessUnit, on_delete=models.SET_NULL, null=True, related_name="cc_set")
    bu_name = models.CharField(max_length=63, null=True)
    bg_name = models.CharField(max_length=63, null=True)
    le_name = models.CharField(max_length=63, null=True)

itms/department/views.py
"""
    Part 1: Cost Center
        cost_center
        add_cost_center
        edit_cost_center
        delete_cost_center
    
    Part 2: Business Unit
        business_unit
        add_business_unit
        edit_business_unit
        delete_business_unit
    
    Part 3: Business Group  (Pending)
        business_group
        add_business_group
        edit_business_group
        delete_business_group
    
    Part 4: Legal Entity (Pending)
        legal_entity
        add_legal_entity
        edit_legal_entity
        delete_legal_entity


"""

from datetime import datetime
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages

from department.models import BusinessUnit, CostCenter, BusinessGroup
from home.app_function import check_permission, get_paginated_obj
from logs.models import CostCenterLog, BusinessUnitLog

"""
    Part 1: Cost Center
        cost_center
        add_cost_center
        edit_cost_center
        delete_cost_center
"""


@login_required
def cost_center(request):
    can_view, msg = check_permission(request.user, "department.view_costcenter")
    if not can_view:
        messages.error(request, f"You do no have permission to View Cost Center. {msg}")
        return redirect("home")
    context = {}
    cost_center_set = CostCenter.objects.order_by("bg_name", "bu_id", "cc_name")

    curr_search = request.GET.get("search", "").strip()
    if curr_search:
        cost_center_set = cost_center_set.filter(
            Q(cc_code__icontains=curr_search)
            | Q(cc_name__icontains=curr_search)
            | Q(cc_manager__icontains=curr_search)
            | Q(bu_name__icontains=curr_search)
            | Q(bg_name__icontains=curr_search)
            | Q(le_name__icontains=curr_search)
        )
        context["curr_search"] = curr_search

    updated_context = get_paginated_obj(
        cost_center_set, request.GET.get("page_num", 1), request.GET.get("page_obj_count", 10)
    )
    context.update(updated_context)

    context["bu_name_list"] = list(BusinessUnit.objects.order_by("bu_name").values_list("bu_name", flat=True))

    return render(request, "department/cost_center.html", context)


@login_required
@csrf_exempt
def add_cost_center(request):
    can_act, msg = check_permission(request.user, "department.change_costcenter")
    if not can_act:
        messages.error(request, f"You do no have permission to Add Cost Center. {msg}")
        return redirect("department:cost_center")

    cc_code = request.POST.get("cc_code", "").strip()
    cc_name = request.POST.get("cc_name", "").strip()
    cc_manager = request.POST.get("cc_manager", "").strip()
    bu_name = request.POST.get("bu_name", "").strip()
    user_name = request.user.username
    # curr_time = datetime.now().astimezone()

    if not cc_code:
        messages.error(request, "CC Code cannot be empty. ")
        return redirect("department:cost_center")

    cc_ref = CostCenter.objects.filter(cc_code=cc_code).first()
    if cc_ref:
        messages.error(request, f"CC {cc_code}[{cc_ref.cc_name}] is already exist. ")
        return redirect("department:cost_center")

    bu_ref = BusinessUnit.objects.filter(bu_name=bu_name).first()
    if bu_ref:
        bg_name = bu_ref.bg_name
        le_name = bu_ref.le_name
    else:
        bg_name = ""
        le_name = ""

    CostCenter.objects.create(
        cc_code=cc_code,
        cc_name=cc_name,
        cc_manager=cc_manager,
        bu=bu_ref,
        bu_name=bu_name,
        bg_name=bg_name,
        le_name=le_name,
    )

    CostCenterLog.create_log("Add", cc_code, user_name, f"{cc_name}({cc_manager}): {bu_name}")

    messages.success(request, f"CC {cc_code} added successfully.")
    return redirect(f"/department/cost_center?search={cc_code}")


@login_required
@csrf_exempt
def edit_cost_center(request):
    can_act, msg = check_permission(request.user, "department.change_costcenter")
    if not can_act:
        messages.error(request, f"You do no have permission to Edit Cost Center. {msg}")
        return redirect("department:cost_center")

    cc_code = request.POST.get("cc_code", "").strip()
    cc_name = request.POST.get("cc_name", "").strip()
    cc_manager = request.POST.get("cc_manager", "").strip()
    bu_name = request.POST.get("bu_name", "").strip()
    user_name = request.user.username
    # curr_time = datetime.now().astimezone()

    if not cc_code:
        messages.error(request, "CC Code cannot be empty. ")
        return redirect("department:cost_center")

    cc_ref = CostCenter.objects.filter(cc_code=cc_code).first()
    if not cc_ref:
        messages.error(request, f"CC {cc_code}[{cc_ref.cc_name}] does not exist. ")
        return redirect("department:cost_center")

    old_cc_name, old_bu_name, old_cc_manager = cc_ref.cc_name, cc_ref.bu_name, cc_ref.cc_manager

    bu_ref = BusinessUnit.objects.filter(bu_name=bu_name).first()

    if bu_ref:
        bg_name = bu_ref.bg_name
        le_name = bu_ref.le_name
    else:
        bg_name = ""
        le_name = ""

    CostCenter.objects.filter(cc_code=cc_code).update(
        cc_code=cc_code,
        cc_name=cc_name,
        cc_manager=cc_manager,
        bu=bu_ref,
        bu_name=bu_name,
        bg_name=bg_name,
        le_name=le_name,
    )

    CostCenterLog.create_log(
        "Edit",
        cc_code,
        user_name,
        f"{old_cc_name}({old_cc_manager}): {old_bu_name} --> {cc_name}({cc_manager}):{bu_name}",
    )

    messages.success(request, f"CC {cc_code} edited successfully.")
    return redirect(f"/department/cost_center?search={cc_code}")


@login_required
@csrf_exempt
def delete_cost_center(request, cc_id):
    can_act, msg = check_permission(request.user, "department.change_costcenter")
    if not can_act:
        messages.error(request, f"You do no have permission to Delete Cost Center. {msg}")
        return redirect("department:cost_center")

    user_name = request.user.username

    cc_ref = CostCenter.objects.filter(id=cc_id).first()
    cc_code = cc_ref.cc_code
    CostCenterLog.create_log(
        "Delete",
        cc_code,
        user_name,
        f"{cc_ref.cc_name}({cc_ref.cc_manager}): {cc_ref.bu_name}: {cc_ref.bg_name}: {cc_ref.le_name}",
    )

    cc_ref.delete()
    messages.success(request, f"CC {cc_code} deleted successfully.")
    return redirect("department:cost_center")


"""
    Part 2: Business Unit
        business_unit
        add_business_unit
        edit_business_unit
        delete_business_unit
"""


@login_required
def business_unit(request):
    can_view, msg = check_permission(request.user, "department.view_businessunit")
    if not can_view:
        messages.error(request, f"You do no have permission to View Business Unit. {msg}")
        return redirect("home")
    context = {}
    business_unit_set = BusinessUnit.objects.order_by("bg_name", "bu_name")

    curr_search = request.GET.get("search", "").strip()
    if curr_search:
        business_unit_set = business_unit_set.filter(
            Q(bu_name__icontains=curr_search)
            | Q(bu_manager__icontains=curr_search)
            | Q(bg_name__icontains=curr_search)
            | Q(le_name__icontains=curr_search)
        )
        context["curr_search"] = curr_search

    updated_context = get_paginated_obj(
        business_unit_set, request.GET.get("page_num", 1), request.GET.get("page_obj_count", 10)
    )
    context.update(updated_context)

    context["bg_name_list"] = list(BusinessGroup.objects.order_by("bg_name").values_list("bg_name", flat=True))

    return render(request, "department/business_unit.html", context)


@login_required
@csrf_exempt
def add_business_unit(request):
    can_act, msg = check_permission(request.user, "department.change_businessunit")
    if not can_act:
        messages.error(request, f"You do no have permission to Add Business Unit. {msg}")
        return redirect("department:business_unit")

    bu_name = request.POST.get("bu_name", "").strip()
    bg_name = request.POST.get("bg_name", "").strip()
    bu_manager = request.POST.get("bu_manager", "").strip()
    le_name = request.POST.get("le_name", "").strip()
    user_name = request.user.username
    # curr_time = datetime.now().astimezone()

    if not bg_name:
        messages.error(request, "Business Group cannot be empty. ")
        return redirect("department:business_unit")

    if not bu_name:
        messages.error(request, "Business Unit cannot be empty. ")
        return redirect("department:business_unit")

    bu_ref = BusinessUnit.objects.filter(bu_name=bu_name).first()
    if bu_ref:
        messages.error(request, f"Business Unit {bu_name} is already exist. ")
        return redirect("department:business_unit")

    bg_ref = BusinessGroup.objects.filter(bg_name=bg_name).first()
    if bg_ref:
        le_name = bg_ref.le.le_name
    else:
        le_name = ""

    BusinessUnit.objects.create(
        bu_name=bu_name,
        bg_name=bg_name,
        bg=bg_ref,
        bu_manager=bu_manager,
        le_name=le_name,
    )

    BusinessUnitLog.create_log("Add", bu_name, user_name, f"{bu_manager}, {bg_name}, {le_name}")

    messages.success(request, f"BU {bu_name} added successfully.")
    return redirect(f"/department/business_unit?search={bu_name}")


@login_required
@csrf_exempt
def edit_business_unit(request):
    can_act, msg = check_permission(request.user, "department.change_businessunit")
    if not can_act:
        messages.error(request, f"You do no have permission to Edit Business Unit. {msg}")
        return redirect("department:business_unit")

    bu_name = request.POST.get("bu_name", "").strip()
    bg_name = request.POST.get("bg_name", "").strip()
    bu_manager = request.POST.get("bu_manager", "").strip()
    user_name = request.user.username
    # curr_time = datetime.now().astimezone()

itms/department/templates/department/business_unit.html
{% extends "root/base_table_list.html" %}
{% load static %}
{% block title %}ITMS Businuss Unit{% endblock %}


{% block header_links %}
<li><i class='far fa-circle'></i> <a href="{% url 'department:cost_center' %}">Cost Center</a></li>
<li><i class='fa fa-circle'></i> <a href="{% url 'department:business_unit' %}">Businuss Unit</a></li>
{% endblock %}

{% block header_nav_bar %}
<form method='GET' id='test_record_form' class='row pe-0'>
    <div class='col-md-2'>
        <input class='form-control' name='search' id='search' placeholder='Search Any Field' value='{{curr_search}}' autofocus='true'>
    </div>
    <div class='col-md-1 btn-row'>
        <button class='btn btn-primary'>Search</button>
    </div>
    <div class='col-md-8'></div>
    <div class='col-md-1 btn-row'>
        <button type='button' class='btn btn-primary' onclick="add_business_unit()">
            Add BU
        </button> 
    </div>
</form>
{% endblock %}

{% block table_list %}
<table class='table table-hover' >
    <thead>
        <tr class='table-header'>
            <th width='10%'>BU Name</th>
            <th width='15%'>BU Manager</th>
            <th width='15%'>BG name</th>
            <th width='15%'>LE Name</th>
            <th width='10%'>Action</th>
        </tr>
    </thead>
    <tbody class='bg-table'>
    {% for bu_ref in objs %}
        <tr>
            <td><a href="{% url 'logs:business_unit_log' %}?search={{bu_ref.bu_name}}">{{bu_ref.bu_name}}</a></td>
            <td>{{bu_ref.bu_manager}}</td>
            <td>{{bu_ref.bg_name}}</td>
            <td>{{bu_ref.le_name}}</td>
            <td>
                <a class='cursor-pointer' title='Edit' 
                    onclick="edit_business_unit('{{bu_ref.bu_name}}', '{{bu_ref.bu_manager}}', '{{bu_ref.bg_name}}')"
                ><i class='fa fa-lg fa-edit'></i></a>
                <a class='cursor-pointer text-danger ms-5' title='Delete' 
                href="{% url 'department:delete_business_unit' bu_id=bu_ref.id %}"
                ><i class='fa fa-lg fa-xmark'></i></a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block script_block %}
<script>
    let bg_name_list = {{bg_name_list|safe}}
</script>
<script src="{% static 'department/business_unit.js' %}"></script>
{% endblock %}

itms/department/templates/department/cost_center.html
{% extends "root/base_table_list.html" %}
{% load static %}
{% block title %}ITMS Cost Center{% endblock %}


{% block header_links %}
<li><i class='fa fa-circle'></i> <a href="{% url 'department:cost_center' %}">Cost Center</a></li>
<li><i class='far fa-circle'></i> <a href="{% url 'department:business_unit' %}">Businuss Unit</a></li>
{% endblock %}

{% block header_nav_bar %}
<form method='GET' id='test_record_form' class='row pe-0'>
    <div class='col-md-2'>
        <input class='form-control' name='search' id='search' placeholder='Search Any Field' value='{{curr_search}}' autofocus='true'>
    </div>
    <div class='col-md-1 btn-row'>
        <button class='btn btn-primary'>Search</button>
    </div>
    <div class='col-md-8'></div>
    <div class='col-md-1 btn-row'>
        <button type='button' class='btn btn-primary' onclick="add_cost_center()">
            Add CC
        </button> 
    </div>
</form>
{% endblock %}

{% block table_list %}
<table class='table table-hover' >
    <thead>
        <tr class='table-header'>
            <th width='10%'>CC</th>
            <th width='20%'>CC Name</th>
            <th width='15%'>CC Manager</th>
            <th width='15%'>BU Name</th>
            <th width='15%'>BG name</th>
            <th width='15%'>LE Name</th>
            <th width='10%'>Action</th>
        </tr>
    </thead>
    <tbody class='bg-table'>
    {% for cc_ref in objs %}
        <tr>
            <td><a href="{% url 'logs:cost_center_log' %}?search={{cc_ref.cc_code}}">{{cc_ref.cc_code}}</a></td>
            <td>{{cc_ref.cc_name}}</td>
            <td>{{cc_ref.cc_manager}}</td>
            <td>{{cc_ref.bu_name}}</td>
            <td>{{cc_ref.bg_name}}</td>
            <td>{{cc_ref.le_name}}</td>
            <td>
                <a class='cursor-pointer' title='Edit' 
                    onclick="edit_cost_center('{{cc_ref.cc_code}}', '{{cc_ref.cc_name}}', '{{cc_ref.cc_manager}}', '{{cc_ref.bu_name}}')"
                ><i class='fa fa-lg fa-edit'></i></a>
                <a class='cursor-pointer text-danger ms-5' title='Delete' 
                href="{% url 'department:delete_cost_center' cc_id=cc_ref.id %}"
                ><i class='fa fa-lg fa-xmark'></i></a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block script_block %}
<script>
    let bu_name_list = {{bu_name_list|safe}}
</script>
<script src="{% static 'department/cost_center.js' %}"></script>
{% endblock %}