itms/account/urls.py
from django.urls import path
from .views import *

app_name = "account"

# Account List
urlpatterns = [
    path("account_assign", account_assign, name="account_assign"),
    path("assign_account_action", assign_account_action, name="assign_account_action"),
    path("delete_account_action", delete_account_action, name="delete_account_action"),
]

# Account Type
urlpatterns += [
    path("account_type", account_type, name="account_type"),
    path("add_account_type", add_account_type, name="add_account_type"),
    path("edit_account_type", edit_account_type, name="edit_account_type"),
    path("delete_account_type/<slug:account_type_id>", delete_account_type, name="delete_account_type"),
]

itms/api/urls.py
from django.urls import path
from .views import *

app_name = "api"

urlpatterns = []

itms/asset/urls.py
from django.urls import path
from .views import *

app_name = "asset"

urlpatterns = [
    path("laptop", laptop, name="laptop"),
    path("add_laptop", add_laptop, name="add_laptop"),
    path("upload_laptop_file", upload_laptop_file, name="upload_laptop_file"),
    path("edit_laptop", edit_laptop, name="edit_laptop"),
    path("delete_laptop", delete_laptop, name="delete_laptop"),
]

urlpatterns += [
    path("monitor", monitor, name="monitor"),
    path("add_monitor", add_monitor, name="add_monitor"),
    path("upload_monitor_file", upload_monitor_file, name="upload_monitor_file"),
    path("edit_monitor", edit_monitor, name="edit_monitor"),
    path("delete_monitor", delete_monitor, name="delete_monitor"),
]

urlpatterns += [
    path("asset_assign", asset_assign, name="asset_assign"),
    path("assign_asset_action", assign_asset_action, name="assign_asset_action"),
    path("delete_asset_action", delete_asset_action, name="delete_asset_action"),
    path("replace_asset_action", replace_asset_action, name="replace_asset_action"),
]

urlpatterns += [
    path("employee_asset_overview/<slug:employee_id>", employee_asset_overview, name="employee_asset_overview"),
    path("print_asset_hand_receipt/<slug:employee_id>", print_asset_hand_receipt, name="print_asset_hand_receipt"),
]

itms/employee/urls.py
from django.urls import path
from .views import *

app_name = "employee"

urlpatterns = [
    path("employee_list", employee_list, name="employee_list"),
    path("add_employee_form", add_employee_form, name="add_employee_form"),
    path("add_employee", add_employee, name="add_employee"),
    path("edit_employee_form/<slug:employee_id>", edit_employee_form, name="edit_employee_form"),
    path("edit_employee", edit_employee, name="edit_employee"),
    path("delete_employee", delete_employee, name="delete_employee"),
    path("deactivate_employee", deactivate_employee, name="deactivate_employee"),
    path("activate_employee", activate_employee, name="activate_employee"),
    path("employee_overview/<slug:employee_id>", employee_overview, name="employee_overview"),
]

itms/itms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("", include("home.urls")),
    path("department/", include("department.urls")),
    path("logs/", include("logs.urls")),
    path("asset/", include("asset.urls")),
    path("employee/", include("employee.urls")),
    path("account/", include("account.urls")),
    path("api/", include("api.urls")),
    path("admin_itms/", include("admin_itms.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itms/asset/models.py
from django.db import models


# Create your models here.
class Asset(models.Model):
    asset_type = models.CharField(max_length=127)
    asset_label = models.CharField(max_length=127, unique=True)
    brand = models.CharField(max_length=127)
    model = models.CharField(max_length=127, null=True)
    serial_number = models.CharField(max_length=127)
    purchase_date = models.DateTimeField(null=True)
    purchase_cost = models.DecimalField(max_digits=9, decimal_places=3)
    status = models.CharField(max_length=15, null=True)  # IDLE, IN_USE, RETIRED
    purchase_order_number = models.CharField(max_length=31, null=True)

    class Meta:
        abstract = True


class Laptop(Asset):
    processor = models.CharField(max_length=127, null=True)
    ram = models.CharField(max_length=15, null=True)
    storage = models.CharField(max_length=15, null=True)


class Monitor(Asset):
    screen_size = models.IntegerField(null=True)
    resolution = models.CharField(max_length=63)

itms/employee/models.py
from django.db import models
from django.db.models import Q
from asset.models import Laptop, Monitor

from department.models import CostCenter


# Create your models here.
class Employee(models.Model):
    employee_id = models.CharField(max_length=31, primary_key=True)
    first_name = models.CharField(max_length=127)
    middle_name = models.CharField(max_length=127, null=True)
    last_name = models.CharField(max_length=127)
    preferred_name = models.CharField(max_length=127, null=True)

    join_date = models.DateTimeField(auto_now_add=True)
    leave_date = models.DateTimeField(null=True)
    active = models.BooleanField(default=True)

    department = models.ForeignKey(CostCenter, on_delete=models.SET_NULL, null=True)
    supervisor = models.CharField(max_length=127)
    email = models.CharField(max_length=127, null=True)
    # laptop = models.ForeignKey(Laptop, on_delete=models.SET_NULL, null=True)
    # monitor = models.ForeignKey(Monitor, on_delete=models.SET_NULL, null=True)

    @property
    def name(self):
        if self.preferred_name:
            return f"{self.preferred_name} {self.last_name}"

        if self.middle_name:
            return f"{self.first_name} {self.middle_name}  {self.last_name}"

        return f"{self.first_name} {self.last_name}"

    @property
    def account_dict(self):
        result = dict(
            self.account_set.exclude(Q(account__isnull=True) | Q(account="")).values_list("account_type_id", "account")
        )
        # print(result)
        return result


class EmployeeAsset(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    asset_type = models.CharField(max_length=127)
    asset_label = models.CharField(max_length=127)
    asset_serial_number = models.CharField(max_length=127)
    asset_brand = models.CharField(max_length=127, null=True)
    asset_model = models.CharField(max_length=127)
    assign_date = models.DateTimeField(auto_now_add=True)
    assign_person = models.CharField(max_length=127)

itms/employee/views.py
from datetime import datetime
from decimal import *
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from account.app_functions import employee_account_needed, employee_leave_company
from account.models import Account, AccountType

from home.app_function import check_permission, get_paginated_obj, json_error, json_success
from employee.models import Employee, EmployeeAsset
from department.models import CostCenter
from logs.models import EmployeeLog


# Create your views here.
@login_required
def employee_list(request):
    can_view, msg = check_permission(request.user, "employee.view_employee")
    if not can_view:
        messages.error(request, f"You do no have permission to view Employee. {msg}")
        return redirect("home")
    context = {}
    employee_set = Employee.objects.all().order_by("department__cc_name", "first_name", "last_name")

    curr_search = request.GET.get("search", "").strip()
    if curr_search:
        employee_set = employee_set.filter(
            Q(employee_id__icontains=curr_search)
            | Q(first_name__icontains=curr_search)
            | Q(middle_name__icontains=curr_search)
            | Q(preferred_name__icontains=curr_search)
            | Q(last_name__icontains=curr_search)
            # | Q(join_date__icontains=curr_search)
            # | Q(leave_date__icontains=curr_search)
            | Q(department__cc_name__icontains=curr_search)
            | Q(department__cc_code__icontains=curr_search)
            | Q(supervisor__icontains=curr_search)
            | Q(active__icontains=curr_search)
        )
        context["curr_search"] = curr_search

    updated_context = get_paginated_obj(
        employee_set, request.GET.get("page_num", 1), request.GET.get("page_obj_count", 10)
    )
    context.update(updated_context)

    return render(request, "employee/employee_list.html", context)


@login_required
@csrf_exempt
def add_employee_form(request):
    can_view, msg = check_permission(request.user, "employee.change_employee")
    if not can_view:
        messages.error(request, f"You do no have permission to Add Employee. {msg}")
        return redirect("employee:employee_list")

    context = {}
    cc_set = CostCenter.objects.all().order_by("bg_name", "bu_id", "cc_name")
    account_type_list = list(AccountType.objects.values_list("account_type", flat=True))
    context["cc_set"] = cc_set
    context["account_type_list"] = account_type_list
    context["curr_date"] = datetime.now().astimezone().strftime("%Y-%m-%d")

    return render(request, "employee/add_employee_form.html", context)


@login_required
@csrf_exempt
def add_employee(request):
    can_view, msg = check_permission(request.user, "employee.change_employee")
    if not can_view:
        messages.error(request, f"You do no have permission to Add Employee. {msg}")
        return redirect("employee:employee_list")
    context = {}

    user_name = request.user.username

    employee_id = request.POST.get("employee_id", "").strip()
    first_name = request.POST.get("first_name", "").strip().capitalize()
    preferred_name = request.POST.get("preferred_name", "").strip().capitalize()
    middle_name = request.POST.get("middle_name", "").strip().capitalize()
    last_name = request.POST.get("last_name", "").strip().capitalize()
    join_date = request.POST.get("join_date", "").strip()
    department = request.POST.get("department", "").strip()
    supervisor = request.POST.get("supervisor", "").strip()
    account_type_list = request.POST.getlist("account_type", [])

    if not department:
        messages.error(request, "Please Select Department. ")
        return redirect("employee:employee_list")

    cc_ref = CostCenter.objects.filter(cc_code=department).first()
    if not cc_ref:
        messages.error(request, f"CC {department} does not exist. ")
        return redirect("employee:employee_list")

    if join_date:
        join_date = datetime.strptime(join_date, "%Y-%m-%d").astimezone()
    else:
        join_date = None

    employee_ref = Employee.objects.filter(employee_id=employee_id).first()
    if employee_ref:
        messages.error(request, f"Employee ID:{employee_id} {employee_ref.name} already exists. ")
        return redirect("employee:employee_list")

    Employee.objects.create(
        employee_id=employee_id,
        first_name=first_name,
        preferred_name=preferred_name,
        middle_name=middle_name,
        last_name=last_name,
        join_date=join_date,
        department=cc_ref,
        supervisor=supervisor,
        active=True,
    )

    # create_log
    EmployeeLog.create_log(
        "Add",
        employee_id,
        f"{first_name} {middle_name}, {last_name} ({preferred_name})",
        f"{cc_ref.cc_code}--{cc_ref.cc_name} ({supervisor})",
        user_name,
        f"{join_date.strftime('%D')}, account_needed: {', '.join(account_type_list)}",
    )

    if account_type_list:
        employee_account_needed(employee_id, account_type_list, request.get_host())

    messages.success(request, f"Employee {employee_id} added successfully.")
    return redirect("employee:employee_list")


@login_required
@csrf_exempt
def edit_employee_form(request, employee_id):
    can_view, msg = check_permission(request.user, "employee.change_employee")
    if not can_view:
        messages.error(request, f"You do no have permission to Edit Employee. {msg}")
        return redirect("employee:employee_list")

    context = {}
    employee_ref = Employee.objects.filter(employee_id=employee_id).first()
    context["employee_ref"] = employee_ref

    cc_set = CostCenter.objects.all().order_by("bg_name", "bu_id", "cc_name")
    context["cc_set"] = cc_set

    employee_account_set = Account.objects.filter(employee_id=employee_id).order_by("id")
    employee_no_account_list = list(
        AccountType.objects.exclude(account_type__in=employee_account_set.values("account_type")).values_list(
            "account_type", flat=True
        )
    )
    context["asset_set"] = EmployeeAsset.objects.filter(employee=employee_ref).order_by("-id")
    context["employee_account_set"] = employee_account_set
    context["employee_no_account_list"] = employee_no_account_list
    return render(request, "employee/edit_employee_form.html", context)


@login_required
@csrf_exempt
def edit_employee(request):
    can_view, msg = check_permission(request.user, "employee.change_employee")
    if not can_view:
        messages.error(request, f"You do no have permission to Edit Employee. {msg}")
        return redirect("employee:employee_list")
    context = {}

    user_name = request.user.username

    employee_id = request.POST.get("employee_id", "").strip()
    first_name = request.POST.get("first_name", "").strip()
    preferred_name = request.POST.get("preferred_name", "").strip()
    middle_name = request.POST.get("middle_name", "").strip()
    last_name = request.POST.get("last_name", "").strip()
    join_date = request.POST.get("join_date", "").strip()
    department = request.POST.get("department", "").strip()
    supervisor = request.POST.get("supervisor", "").strip()
    account_type_list = request.POST.getlist("account_type", [])

    if not department:
        messages.error(request, "Please Select Department. ")
        return redirect("employee:employee_list")

    cc_ref = CostCenter.objects.filter(cc_code=department).first()
    if not cc_ref:
        messages.error(request, f"CC {department} does not exist. ")
        return redirect("employee:employee_list")

    if join_date:
        join_date = datetime.strptime(join_date, "%Y-%m-%d").astimezone()
    else:
        join_date = None

    employee_ref = Employee.objects.filter(employee_id=employee_id).first()
    if not employee_ref:
        messages.error(request, f"Employee {employee_id} does not exist. ")
        return redirect("employee:employee_list")

    employee_ref.employee_id = employee_id
    employee_ref.first_name = first_name
    employee_ref.middle_name = middle_name
    employee_ref.last_name = last_name
    employee_ref.join_date = join_date
    employee_ref.department = cc_ref
    employee_ref.supervisor = supervisor
    employee_ref.preferred_name = preferred_name

    employee_ref.save()
    # employee_ref.refresh_from_db()

    # create_log
    EmployeeLog.create_log(
        "Add",
        employee_id,
        f"{first_name} {middle_name}, {last_name} ({preferred_name})",
        f"{cc_ref.cc_code}--{cc_ref.cc_name} ({supervisor})",
        user_name,
        f"{join_date.strftime('%D')}, account_needed: {', '.join(account_type_list)}",
    )

    if account_type_list:
        employee_account_needed(employee_id, account_type_list, request.get_host())

    messages.success(request, f"Employee {employee_id} edited successfully.")
    return redirect("employee:employee_list")


@login_required
@csrf_exempt
def delete_employee(request):
    can_act, msg = check_permission(request.user, "asset.change_employee")
    if not can_act:
        return json_error(request, f"You do no have permission to delete Employee. {msg}")

    user_name = request.user.username

    employee_id = request.POST.get("employee_id", "").strip()
    comment = request.POST.get("comment", "").strip()

    employee_ref = Employee.objects.filter(employee_id=employee_id).first()
    if not employee_ref:
        return json_error(f"Employee {employee_id} does not exist. ")

    # create_log
    EmployeeLog.create_log(
        "Delete",
        employee_id,
        f"{employee_ref.first_name} {employee_ref.middle_name}, {employee_ref.last_name} ({employee_ref.preferred_name})",
        f"{employee_ref.department.cc_code}--{employee_ref.department.cc_name} ({employee_ref.supervisor})",
        user_name,

itms/employee/templates/employee/edit_employee_form.html
{% extends "root/base_table_list.html" %}
{% load static %}
{% block title %}ITMS Employee{% endblock %}


{% block header_links %}
<li><i class='fa fa-list'></i> <a href="{% url 'employee:employee_list' %}">Employee List</a></li>
<li><i class='fa fa-circle'></i> <a href="{% url 'employee:edit_employee_form' employee_id=employee_ref.employee_id %}">Edit Employee: {{employee_ref.name}}</a></li>
{% endblock %}


{% block body_content %}

<main>
    <section class='wrapper'>
        <form method='POST' action='/employee/edit_employee' id='edit_employee' class='row'>
            {% csrf_token %}

            <div class='col-md-1'></div>
            <div class='col-md-10'>
                <section class='card'>
                    <div id='employee_header' data-bs-toggle="collapse" data-bs-target="#employee_body">
                        <header class="card-header bg-primary fw-bold text-white">
                            Basic Information
                        </header>
                    </div>

                    <div class="card-body">
                        <div id='employee_body' class='collapse show'>
                            <div class='row mt-2'>
                                <div class='col-md-3'>
                                    <label><span class='text-danger'>*</span>Employee ID:</label>
                                    <input class='form-control mt-2' name='employee_id'  readonly value='{{employee_ref.employee_id}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Join Date:</label>
                                    <input type='date' class='form-control mt-2' name='join_date' value='{{employee_ref.join_date | date:"Y-m-d"}}'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                            </div>

                            <div class='row mt-2'>
                                <div class='col-md-3'>
                                    <label><span class='text-danger'>*</span>First Name:</label>
                                    <input class='form-control mt-2' name='first_name'  required value='{{employee_ref.first_name}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Preferred Name:</label>
                                    <input class='form-control mt-2' name='preferred_name' value='{{employee_ref.preferred_name}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label>Middle Name:</label>
                                    <input class='form-control mt-2' name='middle_name' value='{{employee_ref.middle_name}}'>
                                </div>
                                <div class='col-md-3'>
                                    <label><span class='text-danger'>*</span>Last Name:</label>
                                    <input class='form-control mt-2' name='last_name'  required value='{{employee_ref.last_name}}'>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class='card mt-3'>
                    <div id='department_header' data-bs-toggle="collapse" data-bs-target="#department_body">
                        <header class="card-header bg-primary fw-bold text-white">
                            Department
                        </header>
                    </div>
                    <div class="card-body">
                        <div id='department_body' class='collapse show'>
                            <div class='row mt-2'>
                                <div class='col-md-3'>
                                    <label><span class='text-danger'>*</span>Cost Center:</label>
                                    <select name="department" class='form-control mt-2'>
                                        <option value="" disabled selected>-------- Please Select --------</option>
                                        {% for cc in cc_set %}
                                            <option value="{{ cc.cc_code }}" 
                                            {% if cc.cc_code == employee_ref.department.cc_code %}
                                                selected
                                            {% endif %}
                                                >{{ cc.cc_code }} -- {{ cc.cc_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class='col-md-3'>
                                    <label>Supervisor:</label>
                                    <input class='form-control mt-2' name='supervisor' value='{{employee_ref.supervisor}}'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                                <div class='col-md-3'>
                                </div>
                            </div>
                        </div>
                    </div>

                </section>
                {% if employee_account_set %}
                    <section class='card mt-3'>
                        <div id='account_header' data-bs-toggle="collapse" data-bs-target="#account_body">
                            <header class="card-header bg-primary fw-bold text-white">
                                Accounts
                            </header>
                        </div>
                        <div class="card-body">
                            <div id='account_body' class='collapse show'>
                                <div class='row'>
                                    {% for employee_account in employee_account_set %}
                                    <div class='col-md-3 mt-2'>
                                        <label for='{{account_type}}'>&nbsp;{{employee_account.account_type_id}}</label>
                                        <input class='form-control' id='{{account_type}}' name='employee_account' value='{{employee_account.account|default:""}}' readonly placeholder='Pending assign (PIC: {{employee_account.account_type.person_in_charge}} )'>                               

                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </section>
                {% endif %}

                {% if employee_no_account_list %}
                    <section class='card mt-3'>
                        <div id='account_pending_header' data-bs-toggle="collapse" data-bs-target="#account_pending_body">
                            <header class="card-header bg-primary fw-bold text-white">
                                Accounts Need To Be Created
                            </header>
                        </div>

                        <div class="card-body">
                            <div id='account_pending_body' class='collapse show'>
                                <div class='row'>
                                {% for account_type in employee_no_account_list %}
                                    <div class='col-md-3 mt-2'>
                                        <input type='checkbox' class='lg_checkbox ms-2' id='{{account_type}}' name='account_type' value='{{account_type}}'>
                                        <label for='{{account_type}}'>&nbsp;{{account_type}}</label>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </section>
                {% endif %}

                <section class='card mt-3'>
                    <div id='asset_header' data-bs-toggle="collapse" data-bs-target="#asset_body">
                        <header class="card-header bg-primary fw-bold text-white">
                            Assets
                        </header>
                    </div>
                    <div class="card-body">
                        <div id='asset_body' class='collapse show'>
                            <div class='row mt-2'>
                                <div id='asset_body' class='collapse show'>
                                    {% if asset_set %}
                                    <table class='table'>
                                        <thead>
                                            <tr>
                                                <th width='15%'>Category</th>
                                                <th width='15%'>Label</th>
                                                <th width='15%'>SN</th>
                                                <th width='10%'>Brand</th>
                                                <th width='15%'>Model</th>
                                                <th width='15%'>Assign Date</th>
                                                <th width='15%'>Assign Person</th>
                                            </tr>
                                        </thead>
                                        <tbody>                                        
                                            {% for asset in asset_set %}
                                                <tr>
                                                    <td>{{asset.asset_type}}</td>
                                                    <td>{{asset.asset_label}}</td>
                                                    <td>{{asset.asset_serial_number}}</td>
                                                    <td>{{asset.asset_brand}}</td>
                                                    <td>{{asset.asset_model}}</td>
                                                    <td>{{asset.assign_date|date:'Y-m-d H:i'}}</td>
                                                    <td>{{asset.assign_person}}</td>
                                                </tr>
                                                
                                            {% endfor %}                                            
                                        </tbody>
                                    </table>
                                    {% else %}
                                        No asset is assigned to {{employee_ref.name}}
                                    {% endif %}
                            </div>
                        </div>
                    </div>
                </section>
                
            </div>
            <div class='row pe-0'>
                <div class='col-md-10'></div>                
                <div class='col-md-1 mt-5 p-0 btn-row'>
                    <button class='btn btn-primary'>Save</button>
                </div>
                <div class='col-md-1'></div>
            </div>
        </form>
    </section>
</main>

{% endblock %}

itms/employee/templates/employee/employee_list.html
{% extends "root/base_table_list.html" %}
{% load static %}
{% block title %}ITMS Employee{% endblock %}


{% block header_links %}
<li><i class='fa fa-circle'></i> <a href="{% url 'employee:employee_list' %}">Employee List</a></li>
<li><i class='far fa-circle'></i> <a href="{% url 'asset:asset_assign' %}">Assign Asset</a></li>
<li><i class='far fa-circle'></i> <a href="{% url 'account:account_assign' %}">Assign Account</a></li>
{% endblock %}

{% block header_nav_bar %}
<form method='GET' id='test_record_form' class='row pe-0'>
    <div class='col-md-2'>
        <input class='form-control' name='search' id='search' placeholder='Search Any Field' value='{{curr_search}}' autofocus='true'>
    </div>
    <div class='col-md-1 btn-row'>
        <button class='btn btn-primary'>Search</button>
    </div>
    <div class='col-md-8'></div>
    <div class='col-md-1 btn-row'>
            <button type='button' class='btn btn-primary' onclick="location.href='{% url "employee:add_employee_form" %}'">
                Add Employee
            </button>

    </div>
</form>
{% endblock %}

{% block table_list %}
<table class='table table-hover' >
    <thead>
        <tr class='table-header'>
            <th width='10%'>Employee ID</th>
            <th width='15%'>Name</th>
            <th width='10%'>Join Date</th>
            <th width='10%'>Leave Date</th>
            <th width='10%'>CC Code</th>
            <th width='15%'>Department</th>
            <th width='10%'>Supervisor</th>
            <th width='10%'>Active</th>
            <th width='10%'>Action</th>
        </tr>
    </thead>
    <tbody class='bg-table'>
    {% for employee_ref in objs %}
        <tr {% if not employee_ref.active %} class='bg-warning' {% endif %}>
            <td><a href="{% url 'employee:employee_overview' employee_id=employee_ref.employee_id %}" class='cursor-pointer'>{{employee_ref.employee_id}}</a></td>
            <td>{{employee_ref.name}}</td>
            <td>{{employee_ref.join_date | date:'Y-m-d'}}</td>
            <td>{{employee_ref.leave_date | date:'Y-m-d' | default:"-- --"}}</td>
            <td>{{employee_ref.department.cc_code}}</td>
            <td>{{employee_ref.department.cc_name}}</td>
            <td>{{employee_ref.supervisor}}</td>
            <td>{{employee_ref.active}}</td>
            <td>
                <a href="{% url 'employee:edit_employee_form' employee_id=employee_ref.employee_id %}" class='cursor-pointer' title='Edit'><i class='fa fa-lg fa-edit'></i></a>
                {% if employee_ref.account_dict or employee_ref.employeeasset_set.exists %}
                    {% if not employee_ref.active %}
                        <a class='cursor-pointer text-success ms-3' title='Activate'
                            onclick="activate_employee('{{employee_ref.employee_id}}','{{employee_ref.name}}')"
                        ><i class='fa fa-lg fa-check'></i></a>
                    {% else %}
                        <a class='cursor-pointer text-danger ms-3' title='Deactivate'
                            onclick="deactivate_employee('{{employee_ref.employee_id}}','{{employee_ref.name}}')"
                        ><i class='fa fa-lg fa-ban'></i></a>
                    {% endif %}
                {% else %}
                    <a class='cursor-pointer text-danger ms-3' title='Delete'
                        onclick="delete_employee('{{employee_ref.employee_id}}','{{employee_ref.name}}')"
                    ><i class='fa fa-lg fa-xmark'></i></a>
                    
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}


{% block script_block %}

<script src="{% static 'employee/employee.js' %}"></script>

{% endblock %}